spring:
  profiles:
    active: ${ENV}

  application:
    name: portfolio-adama
    user:
      default:
        username: ${APP_DEFAULT_USERNAME}
        password: ${APP_DEFAULT_PASSWORD}

    security:
      jwt:
        secretKey: ${JWT_SECRET_KEY}
        expiration: 2592000000 #one month to milliseconds
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
