version: "3.8"

services:
  springapp:
    restart: on-failure
    build: .
    env_file:
      - .env
    ports:
      - "80:8080"
    volumes:
      - .:/app
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}


