version: "3.0"

services:
  spring-app:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "80:8080"
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}


