services:
  springapp:
    build: .
    platform: linux/amd64
    develop:
      watch:
        - action: rebuild
          path: .
          target: /app
    env_file:
      - .env.local
    ports:
      - "443:8443"
      - "8080:8080"
    volumes:
      - .:/home
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    env_file:
      - .env.local
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}


