version: "3.8"

services:
  springapp:
    restart: on-failure
    build: .
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    ports:
      - "80:8080"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.39
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: portfolio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}


