services:
  springapp:
    build: .
    platform: linux/amd64
    volumes:
      - type: bind
        source: .
        target: /home
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.39
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    name: portfolio_db
