---

- name: Initialize deploy folder on server
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: true
    mode: u=rw,g=rw,o=rw
  loop:
    - "{{ remote_build_dir }}"
    - "{{ release_dir }}"