#- name: Build Portfolio Backend
#  hosts: localhost
#  roles:
#    - build

- name: Initialize Portfolio Backend
  hosts: ionos
  roles:
    - init
  tags:
    - init
    - build
    - deploy

- name: Build Portfolio Backend
  hosts:
    - localhost
    - ionos
  roles:
    - build
  tags:
    - build
    - deploy

- name: Deploy Portfolio Backend
  hosts: ionos
  roles:
    - deploy
  tags:
    - deploy

- name: Copy files
  hosts:
    - ionos
  roles:
    - copy
  tags:
    - copy
    - deploy

- name: Generate SSL certificate
  hosts: ionos
  roles:
    - certbot
  tags:
    - certificate
    - deploy

- name: Clean Portfolio Backend
  hosts: localhost
  roles:
      - clean
  tags:
    - build
    - clean
    - deploy