- name: Initialize Portfolio Backend
  hosts: ionos
  roles:
    - init
  tags:
    - init

# Create archive on localhost and copy it to server then extract it on release folder
- name: Build project
  hosts:
    - localhost
    - ionos
  roles:
      - archive
  tags:
      - archive

# Copy necessary files to release folder
- name: Copy files
  hosts:
    - ionos
  roles:
    - copy
  tags:
    - copy

- name: Generate SSL certificate
  hosts: ionos
  roles:
    - certbot
  tags:
    - certificate

- name: Nginx Configuration
  hosts: ionos
  roles:
    - nginx
  tags:
    - nginx

# Stop old application if exists, link current to new release and start application
- name: Deploy Portfolio Backend
  hosts: ionos
  roles:
    - deploy
  tags:
    - deploy

- name: Clean Portfolio Backend
  hosts:
    - localhost
    - ionos
  roles:
      - clean
  tags:
    - clean